#!/bin/bash
if [ ! -f /usr/share/nginx/html/user/initialized ]
then
  touch /usr/share/nginx/html/user/initialized
  cd /init
  cp -R . /usr/share/nginx/html/user/
fi

if [ ! -h /usr/share/nginx/html/cache ]
then
  cd /usr/share/nginx/html
  rm -rf cache
  ln -s ./user/cache cache
  chmod 777 -R ./user/cache
fi

chown -R www-data:www-data /usr/share/nginx/html
